In [2]:
import numpy as np


In [4]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis=0)

In [9]:
mean_a

array([2. , 8.4])

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
a_centered_t = a_centered.T
a_centered_t

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [27]:
a_centered_t[0], a_centered_t[1]

(array([-1.,  0.,  1.,  1., -1.]), array([-2.4, -0.4,  2.6,  1.6, -1.4]))

In [28]:
a_centered_sp = a_centered_t[0] @ a_centered_t[1]
a_centered_sp

8.0

In [29]:
a_centered_sp / 4

2.0

In [30]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [31]:
a_centered_sp / 4 == np.cov(a.T)[0, 1]

True